list1 = ["Bread", "Milk", "Eggs", "Butter", "Cheese", "Apples", "Bananas", "Chicken", "Rice", "Pasta"]
list2 = ["Prune" , "Peach", "Pear", "Plum", "Pineapple", "Papaya", "Bananas", "Pomegranate", "Rice", "Pumpkin"]
common_items1 = set(list1) ^ set(list2)
common_items2 = set(list1) & set(list2)
common_items3 = set(list1) | set(list2)
common_items4 = set(list1) - set(list2)
print(common_items1)
print(common_items2)
print(common_items3)
print(common_items4)
type(common_items1)
print(type(common_items1))
list1.append("Yogurt")
list1.remove("Butter")
print(list1)
print()